### ISSUE TITLE
Unable to delete stickers

### ISSUE THREAD

**Issue by carnager** [bentglasstube/Net-MPD#9]
Documentation says to use an undefined value to delete a sticker.
So I tried `$mpd->sticker_value("song", "$_", "rating")`
and also `$mpd->sticker_value("song", "$_", "rating", "")`, but both don't work

What is the proper way to do this?

**Comment by carnager** [comment]
Ok, I am stupid. you actually write "undef". Sorry, I am still relatively new to perl.

**Comment by bentglasstube** [comment]
I agree it's a little confusing.  I could certainly improve the
documentation.

Another thing I noticed in your example is the second argument you have is
"$_".  The quotes there are unnecessary and (imho) make it less readable.

--
Alan Berndt

On Sep 30, 2017 04:42, "Rasmus Steinke" <notifications@github.com> wrote:

Ok, I am stupid. you actually write "undef". Sorry, I am still relatively
new to perl.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bentglasstube/Net-MPD/issues/9#issuecomment-333303164>,
or mute the thread
